name: Docker-Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
        services: |
          web
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ClothingShop
        if-no-files-found: error
