# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
    PROJECT_PATH: Web/Web.csproj

on:  
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build release for win10-x64
      run: dotnet publish Web/Web.csproj -c release -r win10-x64

    - name: Build release for linux-x64
      run: dotnet publish Web/Web.csproj -c release -r linux-x64

    - name: Create release archive for win10-x64
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'ClothingShop-release-win10-x64.zip'
        path: Web/bin/Release/net7.0/win10-x64

    - name: Create release archive for linux
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'ClothingShop-release-linux-x64.zip'
        path: Web/bin/Release/net7.0/linux-x64

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "ClothingShop-release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}