# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
    PROJECT_PATH: Web/Web.csproj

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

    - name: Init release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: release
          release_name: release

    - name: Create release archive
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'ClothingShop-release.zip'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        path: Web/bin/Release/net7.0/
        artifacts: "ClothingShop-release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}